export const FETCH_DOG_BREEDS_REQUEST = 'FETCH_DOG_BREEDS_REQUEST';
export const FETCH_DOG_BREEDS_SUCCESS = 'FETCH_DOG_BREEDS_SUCCESS';
export const FETCH_DOG_BREEDS_FAILURE = 'FETCH_DOG_BREEDS_FAILURE';
